security:
  basic:
    enabled: true
  user:
    name: zhanghr
    password: zhanghr
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://zhanghr:zhanghr@localhost:8761/eureka
      
      