package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.Agreement;

public interface AgreementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agreement
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String agreeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agreement
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(Agreement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agreement
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(Agreement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agreement
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    Agreement selectByPrimaryKey(String agreeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agreement
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(Agreement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agreement
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(Agreement record);
}