package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.BillInfo;

public interface BillInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_billinfo
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_billinfo
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(BillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_billinfo
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(BillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_billinfo
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    BillInfo selectByPrimaryKey(String billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_billinfo
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(BillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_billinfo
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(BillInfo record);
}