package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.Pay;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String payid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    Pay selectByPrimaryKey(String payid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(Pay record);
}