package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.ProductBrand;

public interface ProductBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productbrand
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String brandid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productbrand
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(ProductBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productbrand
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(ProductBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productbrand
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    ProductBrand selectByPrimaryKey(String brandid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productbrand
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(ProductBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productbrand
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(ProductBrand record);
}