package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.ProductStore;

public interface ProductStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productstore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String storeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productstore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(ProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productstore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(ProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productstore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    ProductStore selectByPrimaryKey(String storeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productstore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(ProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_productstore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(ProductStore record);
}