package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.ProductType;

public interface ProductTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_producttype
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String producttypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_producttype
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_producttype
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_producttype
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    ProductType selectByPrimaryKey(String producttypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_producttype
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_producttype
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(ProductType record);
}