package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.Score;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    Score selectByPrimaryKey(String scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(Score record);
}