package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.SpecialProstore;

public interface SpecialProstoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_specialprostore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String storeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_specialprostore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(SpecialProstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_specialprostore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(SpecialProstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_specialprostore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    SpecialProstore selectByPrimaryKey(String storeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_specialprostore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(SpecialProstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_specialprostore
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(SpecialProstore record);
}