package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.SystemFlow;

public interface SystemFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_systemflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String flowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_systemflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(SystemFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_systemflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(SystemFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_systemflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    SystemFlow selectByPrimaryKey(String flowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_systemflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(SystemFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_systemflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(SystemFlow record);
}