package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.UserFlow;

public interface UserFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String flowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(UserFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(UserFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    UserFlow selectByPrimaryKey(String flowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(UserFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userflow
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(UserFlow record);
}