package cn.jkm.eb.service.dao;

import cn.jkm.eb.facade.entities.VirtualProduct;

public interface VirtualProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_virtualproduct
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int deleteByPrimaryKey(String producerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_virtualproduct
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insert(VirtualProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_virtualproduct
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int insertSelective(VirtualProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_virtualproduct
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    VirtualProduct selectByPrimaryKey(String producerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_virtualproduct
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKeySelective(VirtualProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_virtualproduct
     *
     * @mbg.generated Wed Jul 12 17:48:15 CST 2017
     */
    int updateByPrimaryKey(VirtualProduct record);
}