package cn.jkm.eb.facade.entities;

public class OrderPayKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderpay.orderPayId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String orderpayid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderpay.orderId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderpay.producer_id
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String producerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderpay.storeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderpay.payId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String payid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderpay.addressId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderpay.agreeID
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String agreeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderpay.orderPayId
     *
     * @return the value of tb_orderpay.orderPayId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getOrderpayid() {
        return orderpayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderpay.orderPayId
     *
     * @param orderpayid the value for tb_orderpay.orderPayId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setOrderpayid(String orderpayid) {
        this.orderpayid = orderpayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderpay.orderId
     *
     * @return the value of tb_orderpay.orderId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderpay.orderId
     *
     * @param orderid the value for tb_orderpay.orderId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderpay.producer_id
     *
     * @return the value of tb_orderpay.producer_id
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getProducerId() {
        return producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderpay.producer_id
     *
     * @param producerId the value for tb_orderpay.producer_id
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setProducerId(String producerId) {
        this.producerId = producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderpay.storeId
     *
     * @return the value of tb_orderpay.storeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderpay.storeId
     *
     * @param storeid the value for tb_orderpay.storeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderpay.payId
     *
     * @return the value of tb_orderpay.payId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderpay.payId
     *
     * @param payid the value for tb_orderpay.payId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setPayid(String payid) {
        this.payid = payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderpay.addressId
     *
     * @return the value of tb_orderpay.addressId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderpay.addressId
     *
     * @param addressid the value for tb_orderpay.addressId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setAddressid(String addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderpay.agreeID
     *
     * @return the value of tb_orderpay.agreeID
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getAgreeid() {
        return agreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderpay.agreeID
     *
     * @param agreeid the value for tb_orderpay.agreeID
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setAgreeid(String agreeid) {
        this.agreeid = agreeid;
    }
}