package cn.jkm.eb.facade.entities;

public class ProductKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.producer_id
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String producerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.orderId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.storeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.payId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String payid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.productTypeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String producttypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.brandId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String brandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.addressId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.agreeID
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String agreeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.billId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String billid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.chatId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    private String chatid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.producer_id
     *
     * @return the value of tb_product.producer_id
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getProducerId() {
        return producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.producer_id
     *
     * @param producerId the value for tb_product.producer_id
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setProducerId(String producerId) {
        this.producerId = producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.orderId
     *
     * @return the value of tb_product.orderId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.orderId
     *
     * @param orderid the value for tb_product.orderId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.storeId
     *
     * @return the value of tb_product.storeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.storeId
     *
     * @param storeid the value for tb_product.storeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.payId
     *
     * @return the value of tb_product.payId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.payId
     *
     * @param payid the value for tb_product.payId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setPayid(String payid) {
        this.payid = payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.productTypeId
     *
     * @return the value of tb_product.productTypeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getProducttypeid() {
        return producttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.productTypeId
     *
     * @param producttypeid the value for tb_product.productTypeId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setProducttypeid(String producttypeid) {
        this.producttypeid = producttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.brandId
     *
     * @return the value of tb_product.brandId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.brandId
     *
     * @param brandid the value for tb_product.brandId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setBrandid(String brandid) {
        this.brandid = brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.addressId
     *
     * @return the value of tb_product.addressId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.addressId
     *
     * @param addressid the value for tb_product.addressId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setAddressid(String addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.agreeID
     *
     * @return the value of tb_product.agreeID
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getAgreeid() {
        return agreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.agreeID
     *
     * @param agreeid the value for tb_product.agreeID
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setAgreeid(String agreeid) {
        this.agreeid = agreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.billId
     *
     * @return the value of tb_product.billId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.billId
     *
     * @param billid the value for tb_product.billId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setBillid(String billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.chatId
     *
     * @return the value of tb_product.chatId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public String getChatid() {
        return chatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.chatId
     *
     * @param chatid the value for tb_product.chatId
     *
     * @mbg.generated Wed Jul 12 17:02:52 CST 2017
     */
    public void setChatid(String chatid) {
        this.chatid = chatid;
    }
}