package cn.jkm.eb.facade.entities;

public class User extends UserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.productid
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderType
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String ordertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderStatus
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String orderstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderAmount
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String orderamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderNum
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderTime
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderRemark
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String orderremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderUnitPrice
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String orderunitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderReason
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String orderreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderUserId
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String orderuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.update_time
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.productid
     *
     * @return the value of tb_order.productid
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.productid
     *
     * @param productid the value for tb_order.productid
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderType
     *
     * @return the value of tb_order.orderType
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderType
     *
     * @param ordertype the value for tb_order.orderType
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderStatus
     *
     * @return the value of tb_order.orderStatus
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderStatus
     *
     * @param orderstatus the value for tb_order.orderStatus
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderAmount
     *
     * @return the value of tb_order.orderAmount
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderAmount
     *
     * @param orderamount the value for tb_order.orderAmount
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrderamount(String orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderNum
     *
     * @return the value of tb_order.orderNum
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderNum
     *
     * @param ordernum the value for tb_order.orderNum
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrdernum(String ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderTime
     *
     * @return the value of tb_order.orderTime
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderTime
     *
     * @param ordertime the value for tb_order.orderTime
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderRemark
     *
     * @return the value of tb_order.orderRemark
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrderremark() {
        return orderremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderRemark
     *
     * @param orderremark the value for tb_order.orderRemark
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrderremark(String orderremark) {
        this.orderremark = orderremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderUnitPrice
     *
     * @return the value of tb_order.orderUnitPrice
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrderunitprice() {
        return orderunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderUnitPrice
     *
     * @param orderunitprice the value for tb_order.orderUnitPrice
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrderunitprice(String orderunitprice) {
        this.orderunitprice = orderunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderReason
     *
     * @return the value of tb_order.orderReason
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrderreason() {
        return orderreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderReason
     *
     * @param orderreason the value for tb_order.orderReason
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrderreason(String orderreason) {
        this.orderreason = orderreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderUserId
     *
     * @return the value of tb_order.orderUserId
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getOrderuserid() {
        return orderuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderUserId
     *
     * @param orderuserid the value for tb_order.orderUserId
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setOrderuserid(String orderuserid) {
        this.orderuserid = orderuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.update_time
     *
     * @return the value of tb_order.update_time
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.update_time
     *
     * @param updateTime the value for tb_order.update_time
     *
     * @mbg.generated Wed Jul 12 16:17:59 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}